"""Add detection models

Revision ID: 4f52a7d949e4
Revises: 8cb7a8329536
Create Date: 2026-08-28 03:45:13.052857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f52a7d949e4'
down_revision: Union[str, Sequence[str], None] = '8cb7a8329536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_case_id'), 'incidents', ['case_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('detection_type', sa.String(length=255), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('rule_version', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_case_id'), 'detections', ['case_id'], unique=False)
    op.create_index(op.f('ix_detections_event_id'), 'detections', ['event_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iocs_case_id'), 'iocs', ['case_id'], unique=False)
    op.create_index(op.f('ix_iocs_event_id'), 'iocs', ['event_id'], unique=False)
    op.create_index(op.f('ix_iocs_evidence_id'), 'iocs', ['evidence_id'], unique=False)
    op.create_table('incident_detections',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'detection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_detections')
    op.drop_index(op.f('ix_iocs_evidence_id'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_event_id'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_case_id'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_detections_event_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_case_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_incidents_case_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
