"""add evidence processing error

Revision ID: 9518428d1b72
Revises: bec51a62f5da
Create Date: 2026-08-26 18:27:53.484075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9518428d1b72'
down_revision: Union[str, Sequence[str], None] = 'bec51a62f5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'processing_error')
    # ### end Alembic commands ###
